export enum EmployeeRole {
  OPERATOR = 'OPERATOR',
  TECHNICIAN = 'TECHNICIAN',
  ENGINEER = 'ENGINEER',
  SUPERVISOR = 'SUPERVISOR',
  MANAGER = 'MANAGER',
  QUALITY_INSPECTOR = 'QUALITY_INSPECTOR',
  MAINTENANCE = 'MAINTENANCE',
  ADMIN = 'ADMIN',
}
