export enum MachineStatus {
  OPERATIONAL = 'OPERATIONAL',
  UNDER_MAINTENANCE = 'UNDER_MAINTENANCE',
  IDLE = 'IDLE',
  OUT_OF_ORDER = 'OUT_OF_ORDER',
  NEEDS_INSPECTION = 'NEEDS_INSPECTION',
  CALIBRATING = 'CALIBRATING',
  RETIRED = 'RETIRED',
}
