export enum PartCategory {
  ENGINE = 'ENGINE',
  SUSPENSION = 'SUSPENSION',
  INTERIOR = 'INTERIOR',
  TRANSMISSION = 'TRANSMISSION',
  ELECTRICAL = 'ELECTRICAL',
  EXTERIOR = 'EXTERIOR',
  BRAKES = 'BRAKES',
  FUEL_SYSTEM = 'FUEL_SYSTEM',
  COOLING = 'COOLING',
  STEERING = 'STEERING',
}
